### ISSUE TITLE
'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by Tangjiandd** [jpmml/pyspark2pmml#39]
"File ""gbdt_train.py"", line 98, in save_model"
"pmmlBuilder = PMMLBuilder(sparksession, df_train, self.piplemodel)"
"File ""/mnt/disk11/yarn/usercache/flowagent/appcache/application_1660093324927_133886/container_e44_1660093324927_133886_02_000001/tmp/py37_spark_2.tar.gz/lib/python3.7/site-packages/pyspark2pmml/__init__.py"", line 12, in __init__"
"javaPmmlBuilder = sc._jvm.org.jpmml.sparkml.PMMLBuilder(javaSchema, javaPipelineModel)"
TypeError: 'JavaPackage' object is not callable

Anyone meet the sample problem?

**Comment by vruusmann** [comment]
> Anyone meet the sample problem?

Unlikely, because everybody else has properly added the JPMML-SparkML JAR file to (Py)Spark classpath before initializing the PySpark2PMML package.

> /tmp/py37_spark_2.tar.gz/lib/python3.7/site-packages/pyspark2pmml/init.py"", line 12, in init"
> "javaPmmlBuilder = sc._jvm.org.jpmml.sparkml.PMMLBuilder(javaSchema, javaPipelineModel)"
> 

There is no such code in `init.py` file, on line 12:
https://github.com/jpmml/pyspark2pmml/blob/0.5.1/pyspark2pmml/__init__.py#L12

Specifically, the following two lines should inform the end user about missing JPMML-SparkML JAR file(s):
https://github.com/jpmml/pyspark2pmml/blob/0.5.1/pyspark2pmml/__init__.py#L13-L14

Therefore, closing this issue as invalid - you're running a very outdated PySpark2PMML package version, plus your PySpark application classpath is incorrect.

FFS, Please follow the README:
https://github.com/jpmml/pyspark2pmml/blob/master/README.md

**Comment by Tangjiandd** [comment]
I has properly added the JPMML-SparkML JAR file to (Py)Spark classpath before initializing the PySpark2PMML package.
I use pyspark2pmml 0.5.1 with jpmml-pyspark 1.5.X
I still meet the error "RuntimeError: JPMML-SparkML not found on classpath" in __init__.py line 14, which jpmml-pyspark may be property for pyspark2pmml 0.5.1 and spark 2.4.7

**Comment by vruusmann** [comment]
> I still meet the error "RuntimeError: JPMML-SparkML not found on classpath" in init.py line 14

If you're seeing this error message - "JPMML-SparkML not found on classpath" - then it means that you haven't set up your PySpark application classpath correctly.

I can't fix your classpath.
